# Generated by Django 2.0.3 on 2018-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=42)),
                ('nazwisko', models.CharField(max_length=42)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
    ]
